### ISSUE TITLE
Poner al dia

### ISSUE THREAD

**Issue by Xavier-LB** [ignacio-magno/lupa-politica#1]
Hola compadre, la pagina esta la raja solo que los datos de los diputados paran en agosto. Que podemos hacer para ponerlo al dia? Siempre me intereso participar en un proyecto de esta onda.

**Comment by ignacio-magno** [comment]
Hola, la razón es que la [https://www.camara.cl/](web oficiail) que provee estos datos solo los ha publicado hasta agosto. Una vez publiquen el software recolectará los datos.

Si te interesa ayudar hablame por privado.
